name: number_selection
description: Custom Number Picker
version: 1.0.0
homepage: https://github.com/geovaniprodata/number_selection

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  awesome_dialog: ^3.2.1
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:

flutter: